Repository samyakmaitre/eventmint, pull requests merged in 2024-11, with the labels that each got.

#478 added user email verification before sending email on forgot password page
  backend/.env
  backend/controllers/auth.js
  package-lock.json
  package.json
  src/components/Auth/PasswordRecovery.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level3

#479 Added a movie Page that was missing in application
  src/App.js
  src/components/MovieImageSlider.js
  src/components/MoviePage.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#480 Added navigation section in offers Page and list show page
  src/components/ListShows.js
  src/components/Offers.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#490 added add shows api
  backend/controllers/Shows.js
  backend/index.js
  backend/models/Shows.js
  src/components/ListShows.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#501 added newsletter frontend backend
  backend/controllers/logo1.png
  backend/controllers/newsletter.js
  backend/index.js
  backend/package-lock.json
  backend/package.json
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#500 made the authorisation better
  backend/controllers/auth.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#499 Fixes for UI and Routing Issues in Eventmint
  src/assets/styles/Play.css
  src/assets/styles/PlaysList.css
  src/components/NavBar.js
  src/components/Play.js
Labels: gssoc-ext, hacktoberfest-accepted, level2
