Repository samyakmaitre/eventmint, pull requests merged in 2024-10, with the labels that each got.

#12 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted

#62 title of webpage updated
  public/index.html
Labels: gssoc-ext, hacktoberfest-accepted

#53 header fixed while scrolling
  src/assets/styles/Header.css
  src/assets/styles/NavBar.css
Labels: hacktoberfest-accepted, level2

#38 Feat: Adding whole logic of login and signup functionality!
  .env
  backend/.env
  backend/config/database.js
  backend/controllers/auth.js
  backend/index.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/App.js
  src/assets/images/login.png
  src/assets/images/signup.png
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Auth/Template.jsx
  src/components/Header.js
  src/components/Home.jsx
  src/components/NavBar.js
  src/index.css
  src/index.js
  src/reducer/index.js
  src/services/apiConnector.js
  src/services/apis.js
  src/services/operations/authAPI.js
  src/slices/authSlice.js
  src/slices/profileSlice.js
  tailwind.config.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level3

#75 #Add Greetings.yml
  .github/workflows/greetings.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#72 Added fevicon
  CODE_of_CONDUCT.md
  CONTRIBUTING.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/license-137276694-2787884.pdf
  src/App.css
  src/App.js
  src/assets/images/theatre.png
  src/assets/styles/Footer.css
  src/components/Footer.js
  src/index.css
  tailwind.config.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level1

#84 Issue #83 resolved: Added hover effects
  package-lock.json
  src/assets/styles/Offers.css
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level1

#77 Additon of All Contributors | Issue #66
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#41 Added Footer
  package.json
  public/index.html
  public/logo192.png
  public/logo512.png
  public/theatre.png
  src/assets/styles/Footer.css
  tailwind.config.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level3

#96 logo update
  package-lock.json
  src/assets/styles/Header.css
  src/components/Header.js
  yarn.lock
Labels: good first issue, gssoc-ext, level1

#102 Feature: Make Logo Clickable to Redirect to Home Page & also add search icon
  src/App.js
  src/assets/styles/Header.css
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#109 Enhance NavBar Functionality and Header Visibility
  package-lock.json
  src/App.js
  src/assets/styles/Header.css
  src/assets/styles/ImageSlider.css
  src/assets/styles/NavBar.css
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Header.js
  src/components/Home.jsx
  src/components/NavBar.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#123 #122 issue enhanced interactivity added
  backend/package-lock.json
  backend/package.json
  package-lock.json
  package.json
  src/components/Header.js
  src/components/ImageSlider.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level1

#119 Search Bar Styling
  package-lock.json
  package.json
  src/assets/styles/Header.css
  src/components/Header.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level1

#118 Google Auth
  package-lock.json
  package.json
  src/components/Auth/Firebase.jsx
  src/components/Auth/LoginForm.jsx
  src/components/Header.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level3

#144 Changed X logo ..
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#139 Add feature: UI improvement and carousal at end , set margins and all too
  src/components/Footer.js
  src/components/Header.js
  src/components/Home.jsx
  src/components/ImageSlider.js
  src/components/MovieList.js
  src/components/NavBar.js
  src/components/Offers.js
  src/components/heading.js
  src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#147 Fixed the top bar in the mobile view
  package-lock.json
  package.json
  public/index.html
  src/components/Header.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level2

#153 Navbar changes, logo added, signing button changes
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/styles/Footer.css
  src/assets/styles/Header.css
  src/assets/styles/ImageSlider.css
  src/assets/styles/Movie.css
  src/assets/styles/MovieList.css
  src/assets/styles/NavBar.css
  src/assets/styles/Offers.css
  src/components/Auth/Firebase.jsx
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Auth/Template.jsx
  src/components/Footer.js
  src/components/Forget.js
  src/components/Header.js
  src/components/Home.jsx
  src/components/ImageSlider.js
  src/components/Movie.js
  src/components/MovieList.js
  src/components/NavBar.js
  src/components/Offers.js
  src/components/heading.js
  src/index.css
  src/index.js
  src/reducer/index.js
  src/reportWebVitals.js
  src/services/apiConnector.js
  src/services/apis.js
  src/services/operations/authAPI.js
  src/setupTests.js
  src/slices/authSlice.js
  src/slices/profileSlice.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#157 Feature/sign in
  package-lock.json
  package.json
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level2

#161 Search Feature
  src/components/Header.js
  src/components/Home.jsx
  src/components/MovieList.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#164 made changes in title
  src/assets/images/removebg.png
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#169 Fixes authslice issue
  src/slices/authSlice.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level1

#154 changes made in text bookmyshow
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#179 Updated Footer component
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#200 ✨added chatbot✨
  src/chatbot.js
  src/components/Home.jsx
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level2

#192 Light and Dark Mode
  src/assets/styles/Header.css
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#191 UI Fixed of footer img & scroll up btn
  src/components/Footer.js
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#189 Improve Navbar UI
  src/components/NavBar.js
  yarn.lock
Labels: gssoc-ext, hacktoberfest-accepted, level2

#159 Navigation Bar Styled Properly
  src/assets/styles/Header.css
  src/assets/styles/NavBar.css
  src/components/NavBar.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#234 [enhancement]: Developed Movie Details Page - Display Movie Information on Card Click
  .gitignore
  package.json
  src/App.js
  src/assets/images/cast1.jpg
  src/assets/images/cast2.jpg
  src/assets/images/cast3.jpg
  src/assets/images/cast4.jpg
  src/assets/images/moviestill1.jpg
  src/assets/images/moviestill2.jpg
  src/assets/images/moviestill3.jpg
  src/assets/styles/MovieDetails.css
  src/components/Movie.js
  src/components/MovieDetails.js
  src/components/MovieList.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#242 Added about us page
  src/App.js
  src/components/AboutUs.js
  src/components/Footer.js
Labels: gssoc-ext, level3, hacktoberfest

#204 Fixed footer dropdown
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#289 fixed logo in header to match with background
  src/assets/images/logo4bg.png
  src/assets/images/removebg.png
  src/assets/images/removedbg.png
  src/assets/styles/Header.css
  src/assets/styles/NavBar.css
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#294 EM9
  package-lock.json
  package.json
  src/App.js
  src/assets/styles/ImageSlider.css
  src/assets/styles/MovieList.css
  src/components/Auth/LoginForm.jsx
  src/components/Auth/SignupForm.jsx
  src/components/Home.jsx
  src/components/ImageSlider.js
  src/components/NavBar.js
  src/components/Offers.js
  src/index.css
  src/validations/validation.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#300 Footer fixations
  src/assets/styles/Header.css
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#301 solved em10
  src/App.css
  src/assets/styles/Movie.css
  src/components/Movie.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#312 New poster4
  src/assets/images/poster4.jpg
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#308 Added a react spinner loader
  package-lock.json
  package.json
  public/index.html
  src/components/Home.jsx
  src/components/Loader.css
  src/components/Loader.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#332 Footer logo updated
  src/components/Footer.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#338 Added Team section in Readme file
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#329 Fixed flex error and Ratings error
  src/assets/styles/MovieDetails.css
  src/components/MovieDetails.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#317 listing show form added
  src/App.js
  src/components/ListShows.js
  src/components/NavBar.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#342 fixed text in login button
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#324 [FIXES #EM6] Add SideMenu to the navbar
  src/assets/styles/Header.css
  src/assets/styles/NavBar.css
  src/assets/styles/SideMenu.css
  src/components/Header.js
  src/components/SideMenu.js
Labels: gssoc-ext, hacktoberfest-accepted, level3

#349 Created Sports Activities Page
  src/App.js
  src/assets/images/sports/sports1.jpg
  src/assets/images/sports/sports2.jpg
  src/assets/images/sports/sports3.jpg
  src/assets/images/sports/sports4.jpg
  src/assets/images/sports/sports5.jpg
  src/assets/images/sports/sportsbanner1.png
  src/assets/images/sports/sportsbanner2.png
  src/assets/images/sports/sportsbanner3.png
  src/assets/styles/Sport.css
  src/assets/styles/SportsDetails.css
  src/assets/styles/SportsList.css
  src/components/NavBar.js
  src/components/Sport.js
  src/components/SportsActivitiesPage.js
  src/components/SportsDetails.js
  src/components/SportsImageSlider.js
  src/components/SportsList.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#343 Update README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#365 Added a scroll back button
  src/App.js
  src/ScrollToTop.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#371 added favicon
  public/index.html
  public/logo3.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#373 removed dark mode
  src/assets/styles/Header.css
  src/components/Header.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#379 added multi language support system✨
  public/index.html
Labels: gssoc-ext, hacktoberfest-accepted, level2

#386 update the style of movie detail page
  src/assets/styles/MovieDetails.css
Labels: gssoc-ext, hacktoberfest-accepted, level2

#407 Update NavBar.css
  src/assets/styles/NavBar.css
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#450 fixed the navbar, header and hamburger-sidebar
  package-lock.json
  src/assets/styles/NavBar.css
  src/components/Header.js
  src/components/ImageSlider.js
  src/components/NavBar.js
  src/components/SideMenu.js
Labels: gssoc-ext, hacktoberfest-accepted, level2

#449 altered the movie-list section
  public/play-button.png
  src/App.css
  src/components/MovieList.js
Labels: gssoc-ext, hacktoberfest-accepted, level1

#458 Added Plays Section
  src/App.js
  src/assets/images/plays/play1.png
  src/assets/images/plays/play2.png
  src/assets/images/plays/play3.png
  src/assets/images/plays/playposter1.jpg
  src/assets/images/plays/playposter2.jpg
  src/assets/images/plays/playposter3.jpg
  src/assets/images/plays/playposter4.jpg
  src/assets/images/plays/playposter5.jpg
  src/assets/styles/Play.css
  src/assets/styles/PlaysList.css
  src/components/Play.js
  src/components/PlaysImageSlider.js
  src/components/PlaysList.js
  src/components/PlaysPage.js
Labels: hacktoberfest-accepted, hacktoberfest

#462 Created a new chatbot !!!
  public/index.html
  src/components/Home.jsx
Labels: gssoc-ext, hacktoberfest-accepted, level2

#403 CSS Styling Contest
  src/App.css
  src/assets/styles/ImageSlider.css
  src/assets/styles/Sport.css
  src/assets/styles/SportsDetails.css
  src/assets/styles/SportsList.css
  src/components/Sport.js
  src/components/SportsDetails.js
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#466 Corrected the x oveflow
  src/App.css
  src/assets/styles/NavBar.css
  src/index.css
Labels: gssoc-ext, hacktoberfest-accepted, level1

#445 added rate limit middleware
  backend/controllers/auth.js
  backend/models/User.js
  backend/package-lock.json
  backend/package.json
Labels: gssoc-ext, hacktoberfest-accepted, level1
